### ISSUE TITLE
i am unable to create an image through your Code

### ISSUE THREAD

**Issue by thesaadmirza** [fiznool/mean-docker-example#1]
I have downloaded your Code ,then follow your code instructions.
`docker build -t fiznool/mean-docker-example .`
It says unable to find the dockerfile.

**Comment by fiznool** [comment]
You need to run the docker command in the directory where the Dockerfile
lives. So if you just cloned this repo, you need to run

cd mean-docker-example

The docker command will then work.

**Comment by thesaadmirza** [comment]
Thanks for the help finzool.
Can you suggest me to get started on meanjs with DOCKER.
i am beginner and want to learn meanjs.

**Comment by fiznool** [comment]
As a beginner I'd suggest you look at and use http://meanjs.org. Come back to this repo when you have a solid foundation in building a mean app!

**Comment by thesaadmirza** [comment]
Thanks.
But i have done going thought your tutorial.
And got this,attaching screenshot.
Now i want to work on how these things are working.
